version: '3.8'

services:
  web:
    build: ./djangobnb_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangobnb_backend/:/usr/src/djangobnb_backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:17.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bnbuser
      - POSTGRES_PASSWORD=djangobnbsecure
      - POSTGRES_DB=djangobnb_db

volumes:
  postgres_data: